apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bookstack-monitor
  namespace: bookstack-dev
  labels:
    release: kube-prometheus-stack 
spec:
  selector:
    matchLabels:
      app: bookstack
  endpoints:
  - port: http
    interval: 30s
    path: /metrics